### ISSUE TITLE
need to implement support for download package from v2 feed

### ISSUE THREAD

**Issue by shrimpy** [NuGet/NuGet.Protocol#11]
currently throwing not implement exception

```
DownloadResource downloadResource = repo.GetResource<DownloadResource>();
            Uri downloadUri = downloadResource.GetDownloadUrl(packageMetadata.Identity).Result;
            Console.WriteLine(downloadUri);
            using (Stream rs = downloadResource.GetStream(packageMetadata.Identity, CancellationToken.None).Result)   // <-- exception from this line
```

```
System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at V2V3Try.V2V3TryProgram.ApiTry(String repoUri, String packageName, String searchTerm) in \\xiaowu-main\xiaowushare\NuGetTry\NuGetV3Try\V2V3Try\V2V3TryProgram.cs:line 174
       at V2V3Try.V2V3TryProgram.nugetV2Try() in \\xiaowu-main\xiaowushare\NuGetTry\NuGetV3Try\V2V3Try\V2V3TryProgram.cs:line 77
       at V2V3Try.V2V3TryProgram.Main(String[] args) in \\xiaowu-main\xiaowushare\NuGetTry\NuGetV3Try\V2V3Try\V2V3TryProgram.cs:line 35
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.NotImplementedException
       HResult=-2147467263
       Message=The method or operation is not implemented.
       Source=NuGet.Client.V2
       StackTrace:
            at NuGet.Client.V2.V2DownloadResource.<GetStream>d__2.MoveNext()
       InnerException: 

```

**Comment by shrimpy** [comment]
seems like this one has been fixed.

**Comment by emgarten** [comment]
Fixed, V2 now calls IPackage.GetStream() to return the package stream.
