### ISSUE TITLE
Installing json.net 6.0.8 throws InvalidOperationException

### ISSUE THREAD

**Issue by swellfr** [NuGet/NuGet.Protocol#29]
To reproduce the error: 
Visual Studio 2015 CTP6 / Nuget 3.0.60225.100

 Create a portable DLL class Profile 259 
 Try to install json.net 6.0.8 

 Package Manager Output:

> Attempting to gather dependencies information for package 'Newtonsoft.Json.6.0.8' with respect to project targeting '.NETPortable, Version=v4.5, Profile=Profile259'

Preview Window pops up and then the exception is thrown

```
System.InvalidOperationException: Sequence contains more than one element
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__d2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
```

**Comment by swellfr** [comment]
I have the same issue with Microsoft.Bcl 1.1.10 on Profile32 (Class Library for Universal Apps)

**Comment by emgarten** [comment]
The fix for this will be in the RC release.

We will soon be disabling issues from this repository and all issues need to be filed at https://github.com/NuGet/Home/issues
