### ISSUE TITLE
should be able to search without filter

### ISSUE THREAD

**Issue by shrimpy** [NuGet/NuGet.Protocol#8]
```
            var searchResource = repo.GetResource<UISearchResource>();
            SearchFilter filter = new SearchFilter();  // SearchFilter filter = null;

// will have to uncomment below code to work-around exceptions
//            List<FrameworkName> fxNames = new List<FrameworkName>();
//            fxNames.Add(new FrameworkName(".NET Framework, Version=4.0"));
//            filter.SupportedFrameworks = fxNames.Select(e => e.ToString());

            IEnumerable<UISearchMetadata> searchResult = searchResource.Search("nuget", filter, 0, 20, CancellationToken.None).Result;
```

Empty filter:
```
System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at V2V3Try.V2V3TryProgram.LocalNuGetTry()
       at V2V3Try.V2V3TryProgram.Main(String[] args)
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.ArgumentNullException
       HResult=-2147467261
       Message=Value cannot be null.
Parameter name: targetFrameworks
       Source=NuGet.Core
       ParamName=targetFrameworks
       StackTrace:
            at NuGet.PackageRepositoryExtensions.Search(IPackageRepository repository, String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions)
            at NuGet.Client.V2.VisualStudio.V2UISearchResource.<GetSearchResultsForVisualStudioUI>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Client.V2.VisualStudio.V2UISearchResource.<Search>d__0.MoveNext()
       InnerException:
```

Null filter:
```
System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at V2V3Try.V2V3TryProgram.LocalNuGetTry() in \\xiaowu-main\xiaowushare\NuGetTry\NuGetV3Try\V2V3Try\V2V3TryProgram.cs:line 83
       at V2V3Try.V2V3TryProgram.Main(String[] args) in \\xiaowu-main\xiaowushare\NuGetTry\NuGetV3Try\V2V3Try\V2V3TryProgram.cs:line 30
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.NullReferenceException
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=NuGet.Client.V2.VisualStudio
       StackTrace:
            at NuGet.Client.V2.VisualStudio.V2UISearchResource.<GetSearchResultsForVisualStudioUI>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Client.V2.VisualStudio.V2UISearchResource.<Search>d__0.MoveNext()
       InnerException:

```

**Comment by shrimpy** [comment]
this one seems to be fixed as well. looking forward to issue #9

**Comment by emgarten** [comment]
Fixed, filters are now initialized to an empty list by default now.
